# cargo-features = ["public-dependency"]
[package]
name = "refimage"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.16", features = [
    "aarch64_simd",
    "wasm_simd",
    "extern_crate_alloc",
] }
# image = { version = "0.25", optional = true }
image = { path = "../image-rs-nofits", optional = true }
num-traits = "0.2"
quick-error = "2.0"
rayon = { version = "1.10", optional = true }
flate2 = { version = "1.0", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
crc32fast = { version = "1.4", optional = true }
# rkyv = { version = "0.7", optional = true }

[dev-dependencies]
color-backtrace = "0.6"

[features]
default = ["rayon", "image", "serde_flate"]
serde = ["dep:serde"]
serde_flate = ["serialize", "serde", "dep:flate2"]
# rkyv = ["serialize", "dep:rkyv"]
serialize = ["dep:crc32fast"]
